### ISSUE TITLE
wekws-ctc训练问题

### ISSUE THREAD

**Issue by kaidachen** [duj12/kws_demo#1]
hi Jean Du,
我尝试在你开源的dctcn预训练模型(mobvoi_kws_transcription/23.pt)基础上使用CTC Loss训练“你好问问/hi小问”唤醒词，目前训练5个epoch，发现cv_acc特别低，且loss下降缓慢。
```
INFO Epoch 0 CV info cv_loss 60.06750510101584 cv_acc 32.3473716624177
INFO Epoch 5 CV info cv_loss 59.136570353712315 cv_acc 33.24977346669095
```
请问是否正常？

**Comment by duj12** [comment]
> 我尝试在你开源的dctcn预训练模型(mobvoi_kws_transcription/23.pt)基础上使用CTC Loss训练“你好问问/hi小问”唤醒词，目前训练5个epoch，发现cv_acc特别低，且loss下降缓慢。

This is normal. For CTC KWS model with just ~1M parameters, it's hard to model all 2599 tokens like big ASR model, so the loss on negative tokens(tokens not relevant to the key words) may be large. 
You can check the loss and acc on the positive samples when you execute validation. I can give you an example:
![image](https://github.com/duj12/kws_demo/assets/37294470/735f4c2d-8a16-4e21-bb6d-f6146e808f12)
In this picture the 1st batch's acc is 75%, and the 2nd batch's acc is 0%, because all positive samples are in 1st batch, and the 2nd batch is full of negative samples. And for this model, the FRR is just 10%, when FAR is 0 per 24 hours. 
You can test the model when you finish the training.

**Comment by kaidachen** [comment]
Thank you for your reply

**Comment by ltcxjtu** [comment]
thanks for these comments
